linters:
  # enable-all: true
  enable:
    - nlreturn
    - wsl
    - varnamelen
    - errcheck
    - errorlint
    - tagliatelle
    - goconst
    - tagalign
    - gochecknoglobals
    - asciicheck
    # - depguard
    - copyloopvar
    - gofmt
    - goimports
    - gomodguard
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - prealloc
    - staticcheck
    - typecheck
    - unconvert
    - unused
    - whitespace