services:
  server:
    build:
      context: .
      target: final
    environment:
      - DATABASE_URL=postgres://postgres:postgres@database:5432/postgres?sslmode=disable
      - MIGRATIONS_PATH=file://migrations
      - SCHEMA_PATH=file://schema.sql
      - DB_DEV_URL=docker://postgres
      - JWT_SECRET_KEY=your_secret_key
      - APP_HOST=localhost:8080
    ports:
      - 8080:8080
    depends_on:
      - database
  database:
    image: postgres:16.3-alpine3.20
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
    ports:
      - 5432:5432
volumes:
  db-data:
