services:
  server:
    build:
      context: .
      target: final
    ports:
      - 3000:3000
    depends_on:
      - database
  database:
    image: postgres:16.3-alpine3.20
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
    ports:
      - 5432:5432
volumes:
  db-data:
