definitions:
  schemas.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  schemas.LoginRequest:
    properties:
      email:
        type: string
      password:
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
  schemas.LoginResponse:
    properties:
      token:
        type: string
    type: object
  schemas.RegisterRequest:
    properties:
      email:
        type: string
      password:
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
  schemas.RegisterResponse:
    properties:
      email:
        type: string
      id:
        type: string
    type: object
info:
  contact: {}
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Login User
      parameters:
      - description: User login info
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/schemas.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: User logged in
          schema:
            $ref: '#/definitions/schemas.LoginResponse'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
      summary: Login User
      tags:
      - Auth
  /register:
    post:
      consumes:
      - application/json
      description: Create New User
      parameters:
      - description: New user info
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/schemas.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: New user created
          schema:
            $ref: '#/definitions/schemas.RegisterResponse'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
      summary: Create New User
      tags:
      - Auth
swagger: "2.0"
